### ISSUE TITLE
是否会增加speed测试国密算法速度功能

### ISSUE THREAD

**Issue by liclicli** [jntass/TASSL#10]
如题，从源码看speed目前不支持测试国密算法的速度，请问近期有相关支持计划吗？

**Comment by jntass** [comment]
我们通过evp的方式支持了sm3和sm4的速度测试。暂时不支持sm2的速度测试。
sm3：openssl speed -evp sm3
sm4：openssl speed -evp sm4

**Comment by liclicli** [comment]
@jntass 非常感谢
