### ISSUE TITLE
请问是否国密标准原则上要求签名私钥要通过硬件分发而且不能从硬件中导出

### ISSUE THREAD

**Issue by XCQi** [jntass/TASSL#14]
最近接触了一个相关的项目，想请问一下：
1.如果以满足国密标准的前提下，是不是必须要通过可信的CA机构签发国密证书，并且应由KMC托管加密私钥，而且使用硬件保存和使用签名私钥？这三个条件都要满足？
2.如果问题1的答案是“是”的话，通过本项目生成的GM/T 0024-2014 体系下的证书 是不是理论上只能用于demo，正式商用的话是不合规的？谢谢您，期望解答

**Comment by taolinke** [comment]
> 
> 
> 最近接触了一个相关的项目，想请问一下：
> 1.如果以满足国密标准的前提下，是不是必须要通过可信的CA机构签发国密证书，并且应由KMC托管加密私钥，而且使用硬件保存和使用签名私钥？这三个条件都要满足？
> 2.如果问题1的答案是“是”的话，通过本项目生成的GM/T 0024-2014 体系下的证书 是不是理论上只能用于demo，正式商用的话是不合规的？谢谢您，期望解答

正式商用是需要openssl和硬件比如HSM结合的。江南天安开源的TASSL是纯软件版本，我们有不开源的版本，支持调度硬件HSM或密码卡，将私钥保存在硬件设备内
