### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by xuai-xc** [jntass/TASSL#2]
./config   执行后 提示

make[1]: 离开目录“/TASSL-master/ssl”
making links in engines...
make[1]: 进入目录“/TASSL-master/engines”
make[1]: *** 没有规则可以创建目标“links”。 停止。
make[1]: 离开目录“/TASSL-master/engines”
make: *** [links] 错误 1

**Comment by jntass** [comment]
由于网络原因，导致上传中出现失败，缺少了文件，现在已经补全缺少的文件，可以编译。请重新下载编译。

**Comment by memdumper** [comment]
编译成功后，如果make install出错，直接执行make install_sw 跳过文档安装部分。
