### ISSUE TITLE
签名数据R S数据长度问题

### ISSUE THREAD

**Issue by WeWebsterchen** [jntass/TASSL#23]
在签名过程中 大素数转化为byte数据过程中发现R S签名数据长度有时是31byte有时是32byte。正常的ECDSA签名数据长度为32。 这个数据长度的原理是什么呢麻烦扫盲下？

**Comment by idleGG** [comment]
256比特的大数向字节数组转换时，若高8bit均为0时，程序会将高位的一个字节丢掉；

**Comment by idleGG** [comment]
256比特的大数向字节数组转换时，若左边9bit均为0时，程序会将高位的一个字节丢掉；
还有一种情况，若最高比特为1，程序还会在高位加8bit的0。
