### ISSUE TITLE
ECDHE密码套件问题

### ISSUE THREAD

**Issue by zhenyuwei** [jntass/TASSL#30]
请教一下，目前测试SM2的ECDHE密码套件，发现两端计算得到的预主密钥不一致，能否查看一下流程是否有异常？

**Comment by zhenyuwei** [comment]
看了一下《GM/T 0009》，发现两端计算预主密钥的时候ID值没有设置，国标《GM/T 0009》里面有ID值，服务端和客户端代码没改全，导致预主密钥计算有问题。

**Comment by jntass** [comment]
tassl里面如果没有设置ID的话，会用采用国标里面默认的1234567812345678作为id进行计算的。

**Comment by zsdevX** [comment]
@zhenyuwei  格尔方便漏个地址出来我调试下？

**Comment by zsdevX** [comment]
@zhenyuwei 我调试了一下 ，两个都可以通（GMSSL和TASSL）。

和TASSL不通可能原因是发送证书顺序引起，属于程序问题。
TASSL的发送证书 先发一个签名证书+根证书+加密证书，其它厂商发送一个签名证书+加密证书+根证书，在处理证书的时候有些厂商认为（写死了）第二个就是加密证书， 因此和TASSL不通。

按照标准 签名证书 接下来就是加密证书 ，估计厂商都是按照这个来做的。

@zhenyuwei 感谢提供测试程序。谢谢

**Comment by zhenyuwei** [comment]
是的，证书链这块根CA可以不需要添加进去，所以证书链这么拼接，看厂商如何处理。
