### ISSUE TITLE
如何单独编译某算法接口及其依赖代码

### ISSUE THREAD

**Issue by a1123622944** [jntass/TASSL#32]
想单独编译SM2的相关接口及其依赖的代码成动态库。单独编译SM3是可以的，SM3并没有太多依赖其他代码，相比之下，SM2依赖其他代码更多，难以编译成库。想知道如何只把SM2的相关接口及其依赖的代码成动态库(不含des,md5等其他算法接口)

**Comment by jntass** [comment]
./config -no-des -no-md5 .....
可参考http://www.169it.com/blog_article/841427108.html
