### ISSUE TITLE
win7平台下 编译32位动态库与静态库错误

### ISSUE THREAD

**Issue by xuai-xc** [jntass/TASSL#44]
.\ssl\s3_srvr.c : error C2220: 警告被视为错误 - 没有生成“object”文件
.\ssl\s3_srvr.c : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请
将该文件保存为 Unicode 格式以防止数据丢失
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio 10.
0\VC\BIN\cl.EXE"”: 返回代码“0x2”
Stop.

**Comment by xuaixcl** [comment]
这个问题如何解决啊，编译不过啊，你们不要刚跟着openssl1.1.b走啊

**Comment by wuyougongzi** [comment]
修改下文件编码就可以了
