### ISSUE TITLE
win7平台32位动态库与静态库编译不过啊

### ISSUE THREAD

**Issue by xuai-xc** [jntass/TASSL#45]
。\ ssl \ s3_srvr.c：错误
C2220：警告被视为错误 - 没有生成“object”文件。\ ssl \ s3_srvr.c：警告C4819：该文件包含不能在当前代码页（936）中表示的字符。请
将该文件保存为Unicode格式以防止数据丢失
NMAKE：致命错误U1077：“”D：\ Program Files（x86）\ Microsoft Visual Studio 10. 
0 \ VC \ BIN \ cl.EXE“”：返回代码“0x2 “ 
停下来。

如何解决这个问题？

**Comment by jntass** [comment]
#44
