### ISSUE TITLE
国密SM2DHE算法中，client是属于发起者吗？

### ISSUE THREAD

**Issue by suishixingkong** [jntass/TASSL#49]
我阅读代码后发现在使用ECDHE-SM4-SM3算法套件时，在计算key的时候是把client作为发起者，把server作为接收者，但在国密SSL VPN文档中并没有提到这个细节，我想知道client到底是不是发起者？？

**Comment by jntass** [comment]
此版本为client端为发起者，国密局检测中server端作为发起者
TASSL-1.1.1k中默认server端作为发起者

https://github.com/jntass/TASSL-1.1.1k

**Comment by jntass** [comment]
此版本中如server端需作为发起方可修改ssl/s3_srvr.c:3016；ssl/s3_clnt.c:3213
