### ISSUE TITLE
请问，ECDHE-SM4-SM3和ECC-SM4-SM3这2个算法套件是否通过了国密的测试，是否真正完全符合国密的标准？？

### ISSUE THREAD

**Issue by suishixingkong** [jntass/TASSL#50]
请问，ECDHE-SM4-SM3和ECC-SM4-SM3这2个算法套件是否通过了国密的测试，是否真正完全符合国密的标准？？

**Comment by jntass** [comment]
TASSL-1.1.1k中两个套件都经过国密测试https://github.com/jntass/TASSL-1.1.1k

此版本中ECDHE-SM4-SM3套件中sm2密钥协商身份与国密测试时不同
