### ISSUE TITLE
ecdhe 互通问题

### ISSUE THREAD

**Issue by Matrix-Zhang** [jntass/TASSL#54]
1）sm2 密钥交换用的密钥是签名证书还是加密证书？
2）我目前在同济的go版本上调试已经通了，因为问题1我可以自己设置，但是和你们的一直互通不了，所以有什么办法可以一起联调吗？

**Comment by Matrix-Zhang** [comment]
目前发现，你们的证书是3张，golang这边是2张，有影响吗？

**Comment by jntass** [comment]
密钥交换使用加密证书，证书只有两张，签名证书/加密证书
