### ISSUE TITLE
这里调整证书加载顺序的依据是什么？是协议要求的吗

### ISSUE THREAD

**Issue by stardrift1** [jntass/TASSL#56]
https://github.com/jntass/TASSL/blob/6e2acf2cbe6e3de1011c7cca967bed3e93b6f0a5/ssl/ssl_cert.c#L1163

**Comment by stardrift1** [comment]
@jntass

**Comment by jntass** [comment]
《GB/T 38636-2020》中定义证书消息，签名证书在前，加密证书在后。
TASSL实现证书消息为签名证书+证书链+加密证书

**Comment by stardrift1** [comment]
> 《GB/T 38636-2020》中定义证书消息，签名证书在前，加密证书在后。 TASSL实现证书消息为签名证书+证书链+加密证书

这边发现babassl和gmssl证书的顺序都是签名证书+加密证书+证书链，是否有考虑过对接场景呢

**Comment by jntass** [comment]
有对接过，此场景下，双方不发送证书链即可。即客户端和服务端证书使用不同的根签发，这样配置根证书，握手时候可以不发送证书链。

至于调整证书顺序，考虑之前版本兼容性，暂时没有计划
