### ISSUE TITLE
关于boost库ssl替换问题

### ISSUE THREAD

**Issue by WeWebsterchen** [jntass/TASSL#7]
目前很多使用P2P通信的时候都是使用boost库里面的功能。看了下boost库下面集成的openssl还是与原本的有些不一样，能否大概说下如果boost库想集成TASSL大概要怎么做。
下图是boost库中ssl的源文件：
![image](https://user-images.githubusercontent.com/30589136/35310819-46a98f02-00ee-11e8-9f51-bc0023f9e89b.png)

**Comment by jntass** [comment]
对boost库不是很了解。如果原来是调用openssl的函数，那么对于集成TASSL还是比较容易的，因为tassl基本是在原openssl基础上增加的对于国密的支持，和原来的openssl的调用基本保持一致。

**Comment by WeWebsterchen** [comment]
TASSL是基于openssl哪个版本更改的。顺便说下能否拉个QQ或者微信群贴出来，有问题直接问效率会高点。

**Comment by jntass** [comment]
目前开源的版本是基于openssl 1.0.2n版本。
我们开源的主要目的是推进国密算法的推广及应用，让你身边的人都知道TASSL，让更多的公司和个人用TASSL，活跃的社区才会减少问题。

**Comment by WeWebsterchen** [comment]
目前源码中没看到JAVA端的源码，有计划什么时候出JAVA和其它语言版本吗？

**Comment by jntass** [comment]
暂时没有java和其他语言，也没有这个计划。
