### ISSUE TITLE
在进行SSL连接时候为什么需要使用加密和签名双证书

### ISSUE THREAD

**Issue by WeWebsterchen** [jntass/TASSL#8]
在openssl中进行ssl握手时候只需要使用单证书进行加密和签名。为什么TASSL SSL连接时签名证书和加密证书必须分开，如果这样的话服务器端最少需要存放3个证书（加密证书对，签名证书对，根证书）。TASSL能否也和openssl一样使用一个证书对既能加密又能签名（目前这样做代码是会报错）？

**Comment by taolinke** [comment]
如果你用的是国际密码套件，是可以单证书的。
如果用国密套件，国密SSL规定必须是双证书体系。

**Comment by WeWebsterchen** [comment]
那有个疑问server端验证client端证书有效性通过SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, verify_callback);回调验证证书有效性，verify_callback回调中ctx传回来的值只有客户端的签名证书以及根证书，是否加密证书没验证是否为BUG？

**Comment by liclicli** [comment]
@WeWebsterchen 我的理解是加密证书实际上是用于传输时的数据加密的，就跟通讯的时候使用一个约定的密码，这个密码是什么并不重要。而解密后的内容是否被篡改是需要验证的部分，所以签名证书需要验证，而加密证书只是用来协商密码的，对解密后的内容没有影响，所以不需要验证

**Comment by zx1234228** [comment]
@taolinke 我用这个替换了Nginx的openssl，想使用国密SSL，按照你都说法是不是要配置一个签名证书和加密证书才可以？

**Comment by taolinke** [comment]
@zx1234228 是的，需要双证书。
